# Based on https://rpi4cluster.com/pxe-ipxe/

on: [push] #foo
jobs:
  make-ipxe:
    name: make ipxe
    runs-on: ubuntu-24.04
    steps:
      - name: checkout self/this
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: self
      - name: checkout ipxe/ipxe github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: v1.21.1 #try to go with latest
          repository: ipxe/ipxe
          path: ipxe
      - name: install ipxe build deps into container
        run: |
          sudo apt update
          sudo apt install -y -d -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 valgrind \
                           gcc-arm-none-eabi gcc-aarch64-linux-gnu
      - name: build ipxe
        run: |
          self_root="${GITHUB_WORKSPACE}/self"
          ipxe_root="${GITHUB_WORKSPACE}/ipxe"
          cp ${self_root}/ipxe_config/config.ipxe ${ipxe_root}/src/
          cp ${self_root}/ipxe_config/general.h ${ipxe_root}/src/config/
          cp ${self_root}/ipxe_config/console.h ${ipxe_root}/src/config/
          cd ${ipxe_root}/src
          make bin-x86_64-efi EMBED=config.ipxe -j2
      - name: upload ipxe.efi as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snponly.efi
          path: ${{ github.workspace }}/ipxe/src/bin-x86_64-efi/snponly.efi
